name: Lint, TypeCheck, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - run: yarn
    - run: yarn --cwd packages/mdsmirror build
    - name: Lint (non-blocking)
      run: yarn lint
      continue-on-error: true
    - run: yarn tc
    - run: yarn test
